config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [ :new, :create ]
    resources :reviews, only: [ :new, :create ]
  end
  resources :doses, only: :destroy
  resources :reviews, only: [ :show, :edit, :update, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, :dependent => :destroy
  has_many :ingredients, through: :doses
  has_many :reviews
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id], :message => "You've already added this ingredient"
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :get_cocktail, only: [ :show, :edit, :update, :destroy ]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @review = Review.new
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save
    return redirect_to cocktail_path(@cocktail) if @cocktail.save
    render :new
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktails_path
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :dose_id, :ingredient_id)
  end

  def get_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def show
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    return redirect_to @cocktail if @dose.save
    redirect_to @cocktail
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new
  end

  def show
  end

  def create
    @review = Review.new(review_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review.cocktail = @cocktail
    return redirect_to cocktail_path(@review.cocktail) if @review.save
    render :new
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to cocktail_path(@review.cocktail)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_navbar.html.erb
<div class="navbar">
  <div class="navbar-logo">
  <%= link_to cocktails_path, :action => 'go' do %>
    Cocktail<b>Planet</b>
  <% end %>
  </div>
  <div class="navbar-icon">
  <%= link_to cocktails_path, :action => 'go' do %>
    <i class="fas fa-cocktail fa-spin"></i>
  <% end %>
  </div>
  <%= link_to new_cocktail_path, :action => 'go' do %>
  <div class="navbar-add">
    Add a cocktail
  </div>
  <% end %>
</div>

app/views/cocktails/edit.html.erb
<%= render './cocktails/navbar' %>
<div class="container">
  <div class="wrapper-form">
    <h1>Edit cocktail (<%= @cocktail.name %>)</h1>
    <%= form_for(@cocktail) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, :value => @cocktail.name %>
    <br/>
    <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/cocktails/index.html.erb
<%= render 'navbar' %>

<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <div class="col-xs-12 col-md-4">
      <div class="card">
        <%= link_to cocktail_path(cocktail), :action => 'go' do %>
        <div class="card-body">
          <h2><%= cocktail.name %></h2>
          <ul>
            <% cocktail.doses[0..2].each do |dose| %>
            <li>
              <%= dose.ingredient.name %>
            </li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <div class="card-footer">
          <%= link_to "Edit", edit_cocktail_path(cocktail) %> |
          <%= link_to "Delete", cocktail_path(cocktail), method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<%= render 'navbar' %>
<div class="container">
  <div class="wrapper-form">
    <h1>Add a cocktail</h1>
    <%= form_for(@cocktail) do |f| %>
    <%= f.label :name %>
    <br/>
    <%= f.text_field :name, :value => @cocktail.name, :class => 'txt-field' %>
    <br/><br/><br/><br/>
    <%= f.submit 'Add cocktail', :class => 'add-button' %>
    <% end %>
  </div>
</div>

app/views/cocktails/show.html.erb
<%= render 'navbar' %>

<div class="container">
  <div class="container-flex">
    <div class="wrapper-image">
      <div class="top-row">
        <h1><%= @cocktail.name %></h1>
        <h2>Ingredients</h2>
        <ul>
          <% @cocktail.doses.each do |dose| %>
            <li>
              <%= dose.ingredient.name %>
              (<%= dose.description %>) |
              <%= link_to "Delete", dose_path(dose), class: "delete-text", method: :delete, data: { confirm: "Are you sure?" } %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="bottom-row">
        <h2>Reviews</h2>
        <ul>
          <% @cocktail.reviews.each do |review| %>
            <li>
              <% review.rating.times do %>
              <i class="fas fa-star"></i>
              <% end %>
              <%= review.content %> |
              <%= link_to "Delete", review_path(review), class: "delete-text", method: :delete, data: { confirm: "Are you sure?" } %>
            </li>
          <% end %>
        </ul>
        <%= link_to "Back to index", cocktails_path %>
      </div>
    </div>
    <div class="wrapper-form form-1">
      <h1>Add an ingredient</h1>
      <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.association :ingredient, as: :select %>
      <%= f.input :description, label: "Dose" %>
      <%= f.submit "Add ingredient", class: "add-button" %>
      <% end %>
      <div class="formimg"><br/>
        <img src='http://s1.1zoom.me/big0/1/Juice_Orange_fruit_Grapes_Fruit_Highball_glass_521682_1280x853.jpg' class="form-image">
      </div>
    </div>
    <div class="wrapper-form form-2">
      <h1>Review this cocktail</h1>
      <% @rating_options = [0, 1, 2, 3, 4, 5] %>
      <%= simple_form_for [@cocktail, @review] do |f| %>
      <%= f.input :rating, as: :select, collection: 0..5 %>
      <%= f.input :content, label: "What did you think?" %>
      <%= f.submit "Add review", class: "add-button" %>
      <% end %>
      <div class="formimg">
        <img src='http://s1.1zoom.me/b5050/745/contractBusiness_503728_2880x1800.jpg' class="form-image">
      </div>
    </div>

  </div>
</div>

app/views/doses/new.html.erb
<%= render './cocktails/navbar' %>
<div class="container">
  <div class="wrapper-form">
    <h1>Add an ingredient</h1>
    <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.association :ingredient, as: :select %>
    <%= f.input :description, label: "Dose" %>
    <%= f.submit "Add ingredient", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>